#!/bin/bash

BUCKET=ota.example.com

source $(dirname $0)/s3vars.sh
bundle exec s3sync sync --exclude="^ota[.].*|sync|s3vars[.]sh|Gemfile.*|[.]rvmrc|[.]DS_Store|[.]ruby-.*$" "$@" $(dirname $0) $BUCKET:
